//generated by claude
include <BOSL2/std.scad>
include <BOSL2/threading.scad>

// M60 nut parameters
thread_diameter = 60;     // M60
thread_pitch = 1.5;       // 1.5mm pitch
nut_thickness = 10;       // 10mm thick
hex_size = 90;            // Across-flats dimension
chamfer_size = 1.5;       // Chamfer size in mm

// Create the nut with chamfered edges
difference() {
    // Hexagonal outer shape with chamfers on top and bottom edges
    cyl(
        h=nut_thickness, 
        d=hex_size/cos(30), 
        chamfer=chamfer_size,
        $fn=6,
        anchor=BOTTOM
    );
    
    // Threaded hole with chamfered entry/exit
    union() {
        // Main threaded hole
        threaded_rod(
            d=thread_diameter, 
            l=nut_thickness,
            pitch=thread_pitch,
            internal=true,
            anchor=BOTTOM
        );
        
        // Top chamfer on thread hole
        translate([0, 0, nut_thickness])
            cylinder(h=chamfer_size, r1=thread_diameter/2, r2=thread_diameter/2 + chamfer_size, $fn=60);
        
        // Bottom chamfer on thread hole
        translate([0, 0, 0])
            cylinder(h=chamfer_size, r1=thread_diameter/2 + chamfer_size, r2=thread_diameter/2, $fn=60);
    }
}